messagetype: text
info:
   noargs: "ğŸ«µå‘½ä»¤é”™è¯¯,è¯·æŸ¥çœ‹å¸®åŠ©!"
   nopermissions: "ğŸ«µæ²¡æœ‰ä½¿ç”¨æƒé™!"
   noresults: "ğŸ«µå•¥ä¹Ÿæ²¡æ‰¾åˆ°!"
   requestfail: "ğŸ˜¤èµ„æºæŸ¥æ‰¾å¤±è´¥!"
        
        